name: publish

on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      version:
        description: 'Version'
        required: true

jobs:

  publish:
    runs-on: ubuntu-latest

    permissions:
      packages: write
      contents: read
      id-token: write

    strategy:
      fail-fast: false
      matrix:
        # https://hub.docker.com/_/php/
        php-version:
          - '8.2-fpm'
          - '8.3-fpm'
          - '8.3-cli'

    env:
      IMAGE_REGISTRY: ghcr.io
      IMAGE_LATEST: '8.3-fpm'

    steps:
      - uses: docker/setup-qemu-action@v3

      - uses: docker/setup-buildx-action@v3

      - uses: docker/login-action@v3
        with:
          registry: ${{ env.IMAGE_REGISTRY }}
          username: ${{ github.repository_owner }}
          password: ${{ secrets.PACKAGES_GITHUB_PAT }}

      # https://github.com/docker/metadata-action?tab=readme-ov-file#outputs
      - uses: docker/metadata-action@v5
        id: meta
        with:
          images: |
            ${{ env.IMAGE_REGISTRY }}/${{ github.repository }}
          tags: |
            type=raw,value=${{ matrix.php-version }}
            type=raw,value=latest,enable=${{ matrix.php-version == env.IMAGE_LATEST }}
          labels: |
            maintainer=Veaceslav Medvedev <slavcopost@gmail.com>
            org.opencontainers.image.licenses=MIT
            org.opencontainers.image.vendor=slavcodev

      - run: |
          echo "${{steps.meta.outputs.version}}"
          echo "${{steps.meta.outputs.tags}}"
          echo "${{steps.meta.outputs.labels}}"

      - uses: docker/build-push-action@v6
        id: push
        with:
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: "PHP_VERSION=${{ matrix.php-version }}"
