name: publish

on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      version:
        description: 'Version'
        required: true

jobs:

  publish:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        # https://hub.docker.com/_/php/
        php-version:
          - '8.2-fpm'
          - '8.3-fpm'
          - '8.3-cli'

    env:
      IMAGE_NAME: $( echo ghcr.io/${GITHUB_REPOSITORY} )
      IMAGE_LATEST: '8.3-fpm'

    steps:
      - uses: actions/checkout@v2

      - name: "Login to registry"
        run: echo "${{ secrets.PACKAGES_GITHUB_PAT }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: "Build the Docker image"
        run: |
          docker build . \
            --file Dockerfile \
            --tag ${{ env.IMAGE_NAME }}:${{ matrix.php-version }} \
            --build-arg PHP_VERSION=${{ matrix.php-version }}

      - name: "Tag alias image (manual)"
        if: github.event_name == 'workflow_dispatch'
        run: |
          docker tag \
            ${{ env.IMAGE_NAME }}:${{ matrix.php-version }} \
            ${{ env.IMAGE_NAME }}:${{ github.event.inputs.version }}-${{ matrix.php-version }}

      - name: "Tag alias image (release)"
        if: github.event_name == 'release'
        run: |
          docker tag \
            ${{ env.IMAGE_NAME }}:${{ matrix.php-version }} \
            ${{ env.IMAGE_NAME }}:$( echo ${GITHUB_REF#"refs/tags/"} )-${{ matrix.php-version }}

      - name: "Tag latest image"
        if: matrix.php-version == env.IMAGE_LATEST
        run: |
          docker tag \
            ${{ env.IMAGE_NAME }}:${{ matrix.php-version }} \
            ${{ env.IMAGE_NAME }}:latest

      - name: "Publish the Docker image"
        run: docker push -a ${{ env.IMAGE_NAME }}
